# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  desc "Atlas deterministic code intelligence: symbols, calls, routes, impact, cross-repo."
  homepage "https://github.com/aziron-ai/atlas"
  version "0.1.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  on_macos do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.22/atlas_0.1.22_darwin_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "46f36a9a5b963da066176abf2cc172e183ecdf5cc5102fd67d757610a8c9641e"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.22/atlas_0.1.22_darwin_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "f2fd405b04761f48eb7827e8093e9db4fc18b1c7f6c9b40a14061cb7a5d725b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.22/atlas_0.1.22_linux_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "c9db4f9a2755b3a08495eb92acc1d97feeb03a993116eb9ad8633533cddbad09"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.22/atlas_0.1.22_linux_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "34ff8f2a3283b626382b7b41d77f7a0ccd9b73a86000b02943fa57961f78365c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
  end

  # No zap stanza required
end
