# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  desc "Atlas deterministic code intelligence: symbols, calls, routes, impact, cross-repo."
  homepage "https://github.com/aziron-ai/atlas"
  version "0.1.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  on_macos do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.34/atlas_0.1.34_darwin_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "05d065e9b7a9d6cf1347ffcd3c8df831326a32eb34e3e2feda8eeefbadd01374"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.34/atlas_0.1.34_darwin_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "8aed273752c1d6c781bf2800fce6a60cc3bb2f89d9eb88579ccff3c8c54f1373"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.34/atlas_0.1.34_linux_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "3647a988a67886db5b1c5a43ae4a24be06216b6d8f34a4e7141787fbefe87f4f"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.34/atlas_0.1.34_linux_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "6ab40b466415825436aba2610412a60e9522128188c34ced1eef5f1766a67201"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
    # Auto-provision the atlas skill + MCP config for every assistant on this
    # machine (Claude desktop+CLI, Codex, Copilot, Cursor, Gemini). Runs as the
    # installing user with HOME available; best-effort so a provisioning hiccup
    # never fails the cask install.
    begin
      system_command "#{staged_path}/atlas", args: ["bootstrap"]
    rescue
      # ignore: `atlas bootstrap` (or first-run) can be run manually later
    end
  end

  # No zap stanza required
end
